### ISSUE TITLE
Investigate Exception when multiple jobs start on a single task

### ISSUE THREAD

**Issue by ngruelaneo** [aneoconsulting/ArmoniK#101]
when sending multiple tasks in same session ( about 500 to 1000 )we have an 'ENHANCE_YOUR_CALM' error cf below

 

How to reproduce :

 

In client add line in bold

 
```csharp
    private static void ClientStartup2(SessionService sessionService)
    {
      var numbers = new List<int>
      {
        2,
      };

      var clientPayload = new ClientPayload
      {
        numbers = numbers,
        Type    = ClientPayload.TaskType.ComputeCube,
      };

      var payload        = clientPayload.Serialize();
      var outputMessages = new StringBuilder();
      outputMessages.AppendLine("In this series of samples we're creating N jobs of one task.");
      outputMessages.AppendLine(@"In the loop we have :
        1 sending job of one task
        2 wait for Result
        3 get associated payload");

            N_Jobs_of_1_Task_With_Results_At_The_End(sessionService, payload, 1, outputMessages); // ok
            N_Jobs_of_1_Task_With_Results_At_The_End(sessionService, payload, 10, outputMessages); // ok
            N_Jobs_of_1_Task_With_Results_At_The_End(sessionService, payload, 1000, outputMessages); //exception
    }
 ```

Then add this test method :

 

```
        private static void N_Jobs_of_1_Task_With_Results_At_The_End(SessionService sessionService, byte[] payload, int nbJobs, StringBuilder outputMessages)
        {
            var sw = Stopwatch.StartNew();
            List<string> taskIds = new List<string>(nbJobs);
            for (var i = 0; i < nbJobs; i++)
            {
                //Thread.Sleep(100); => uncomment this to fix the issue
                string taskId = sessionService.SubmitTask(payload);
                taskIds.Add(taskId);
            }

            outputMessages.AppendLine($"Client called (Results_At_The_End) {nbJobs} jobs of one task in {sw.ElapsedMilliseconds / 1000} sec (only job creation time)");

            var finalResult = 0;
            while (taskIds.Count > 0)
            {
                sw.Restart();
                List<Tuple<string, byte[]>> results = sessionService.TryGetResults(taskIds).ToList();
                var requestedTaskCount = taskIds.Count;
                foreach (Tuple<string, byte[]> resultItem in results)
                {
                    ClientPayload result = ClientPayload.Deserialize(resultItem.Item2);
                    if (result.Result == 0)
                        Log.Error($"The taskId {resultItem.Item1} returns [{result.Result}]");

                    finalResult += result.Result;
                    taskIds.Remove(resultItem.Item1);
                }
                outputMessages.AppendLine($"  => requested/received {requestedTaskCount}/{results.Count} in {sw.ElapsedMilliseconds / 1000} sec (only job creation time)");
            }
            var elapsedMilliseconds = sw.ElapsedMilliseconds;
            outputMessages.AppendLine($"Client called (Results_At_The_End) {nbJobs} jobs of one task in {elapsedMilliseconds / 1000} sec agregated Result = {finalResult}");
        }

```
 

Exception is :

```
[17:25:41 DBG] payload with dependencies 1
[17:25:41 DBG] Create task cc95a85a-41c7-4143-b252-74e7db6e7b9d
[17:25:41 DBG] Tasks created : ["cc95a85a-41c7-4143-b252-74e7db6e7b9d"]
[17:25:41 DBG] payload with dependencies 1
[17:25:41 DBG] Create task d3e5c3af-cf09-4e2d-9dac-66bc8d88039b
Unhandled exception. System.AggregateException: One or more errors occurred. (Status(StatusCode="ResourceExhausted", Detail="Error starting gRPC call. HttpRequestException: An error occurred while sending the request. IOException: The request was aborted. Http2StreamException: The HTTP/2 server reset the stream. HTTP/2 error code 'ENHANCE_YOUR_CALM' (0xb).", DebugException="System.Net.Http.HttpRequestException: An error occurred while sending the request.
---> System.IO.IOException: The request was aborted.
---> System.Net.Http.Http2StreamException: The HTTP/2 server reset the stream. HTTP/2 error code 'ENHANCE_YOUR_CALM' (0xb).
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders()
   at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)"))
---> Grpc.Core.RpcException: Status(StatusCode="ResourceExhausted", Detail="Error starting gRPC call. HttpRequestException: An error occurred while sending the request. IOException: The request was aborted. Http2StreamException: The HTTP/2 server reset the stream. HTTP/2 error code 'ENHANCE_YOUR_CALM' (0xb).", DebugException="System.Net.Http.HttpRequestException: An error occurred while sending the request.
---> System.IO.IOException: The request was aborted.
---> System.Net.Http.Http2StreamException: The HTTP/2 server reset the stream. HTTP/2 error code 'ENHANCE_YOUR_CALM' (0xb).
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders()
   at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")
   at ArmoniK.Extensions.Common.StreamWrapper.Client.SubmitterClientExt.CreateTasksAsync(SubmitterClient client, String sessionId, TaskOptions taskOptions, IEnumerable`1 taskRequests, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at ArmoniK.DevelopmentKit.SymphonyApi.Client.api.SessionService.SubmitTasksWithDependencies(IEnumerable`1 payloadsWithDependencies)
   at ArmoniK.DevelopmentKit.SymphonyApi.Client.api.SessionServiceExt.SubmitTask(SessionService client, Byte[] payload)
   at Armonik.Samples.Symphony.Client.Program.N_Jobs_of_1_Task_With_Results_At_The_End(SessionService sessionService, Byte[] payload, Int32 nbJobs, StringBuilder outputMessages) in C:\Users\UT33NH\aneo\armonik-v2.5.1\source\ArmoniK.Samples\Samples\SymphonyLike\ArmoniK.Samples.SymphonyClient\Program.cs:line 281
   at Armonik.Samples.Symphony.Client.Program.ClientStartup2(SessionService sessionService) in C:\Users\UT33NH\aneo\armonik-v2.5.1\source\ArmoniK.Samples\Samples\SymphonyLike\ArmoniK.Samples.SymphonyClient\Program.cs:line 226
   at Armonik.Samples.Symphony.Client.Program.Main(String[] args) in C:\Users\UT33NH\aneo\armonik-v2.5.1\source\ArmoniK.Samples\Samples\SymphonyLike\ArmoniK.Samples.SymphonyClient\Program.cs:line 116

Aborted (core dumped)

 ```

Rem : in the code if we add ‘Thread.Sleep(100);’ we do not have this issue anymore

**Comment by aneojgurhem** [comment]
The lack of stream.requestStream.completeasync actually
