### ISSUE TITLE
Key not found in core HTCmock

### ISSUE THREAD

**Issue by lemaitre-aneo** [aneoconsulting/ArmoniK#228]
**Describe the bug**

Almost always, htcmock hangs after one of the pod get the following error
```
ArmoniK.Core.Common.Exceptions.ObjectDataNotFoundException: Key not found
   at ArmoniK.Core.Adapters.Redis.ObjectStorage.GetValuesAsync(String key, CancellationToken cancellationToken)+MoveNext() in /src/Adaptors/Redis/src/ObjectStorage.cs:line 126
   at ArmoniK.Core.Adapters.Redis.ObjectStorage.GetValuesAsync(String key, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Select.cs:line 221
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:line 70
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:line 75
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|424_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|424_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
   at ArmoniK.Core.Common.Pollster.DataPrefetcher.PrefetchDataAsync(TaskData taskData, CancellationToken cancellationToken) in /src/Common/src/Pollster/DataPrefetcher.cs:line 105
   at ArmoniK.Core.Common.Pollster.Pollster.MainLoop(CancellationToken cancellationToken) in /src/Common/src/Pollster/Pollster.cs:line 152
```

**To Reproduce**
1. Deploy ArmoniK with core htcmock worker and at least 2 worker pods
2. start core htcmock client with 1000 tasks and 1 level
3. Check seq to see the error
4. At this point, one of the pod is looping on `Task {taskId} already acquired by {OtherOwnerPodId}`

**Expected behavior**

There is 2 expected behaviors:
- The key not found error should not be there at all
- In case of error, the task should be processed by another pod

**Screenshots**

![image](https://user-images.githubusercontent.com/91961298/172552314-ffa7d737-c2b8-4f39-b4bd-3b062a8e038e.png)
![image](https://user-images.githubusercontent.com/91961298/172552377-6b45fb41-a7d5-42d7-88f8-66343e8bc487.png)

**Infra**
- Target (Local, AWS, Docker compose, etc..) : local
- Queue (Activemq managed or not) : activemq in kube
- DataBase (MongoDB) : mongodb in kube
- Cache (Redis managed or not) : redis in kube
- Infra Version : b1559ae0f95b64f57f365f46067a76255d119c82 (db/nonrootdocker)
- Core Images and Version (if known) : 0.5.11-SNAPSHOT.85.06231c1 
- Worker Image and Version (if known) : 0.5.11-SNAPSHOT.85.06231c1  htcmock

**Additional context**
It seems that it is always the task with taskid `*#root.1000` that fails.

**Comment by lemaitre-aneo** [comment]
After some check, I can tell that it has been introduced by https://github.com/aneoconsulting/ArmoniK.Core/pull/67
Reverting this merge makes this bug disappear.

**Comment by aneojgurhem** [comment]
Fixed by https://github.com/aneoconsulting/ArmoniK.Core/pull/72
